// <auto-generated />
using System;
using GoodBurguer.GoodBurguer.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodBurguer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423144832_InserirProdutosPadrao")]
    partial class InserirProdutosPadrao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodBurguer.GoodBurguer.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItensPedido", (string)null);
                });

            modelBuilder.Entity("GoodBurguer.GoodBurguer.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("GoodBurguer.GoodBurguer.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f3c9b2-7d4e-4a1b-9c2e-1f7d8a2b3c4d"),
                            Ativo = true,
                            Nome = "X Burger",
                            Preco = 5.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("b2e4d6a8-9c1f-4d3a-b7e2-2c8f9a1b5d6e"),
                            Ativo = true,
                            Nome = "X Egg",
                            Preco = 4.50m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("c3d5e7f9-1a2b-4c3d-8e9f-3b7c6d5e4f2a"),
                            Ativo = true,
                            Nome = "X Bacon",
                            Preco = 7.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("d4e6f8a1-2b3c-4d5e-9f0a-4c8d7e6f5a3b"),
                            Ativo = true,
                            Nome = "Batata frita",
                            Preco = 2.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("e5f7a9b2-3c4d-5e6f-0a1b-5d9e8f7a6b4c"),
                            Ativo = true,
                            Nome = "Refrigerante",
                            Preco = 2.50m,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("GoodBurguer.GoodBurguer.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("GoodBurguer.GoodBurguer.Domain.Entities.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoodBurguer.GoodBurguer.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
